- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start and enable nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: delete html directory
    ansible.builtin.file:
      path : cd /usr/share/nginx/html
      state: absent
  - name: create file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
  - name: download the code
    ansible.builtin.get_url:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unarchive the file
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest:  /usr/share/nginx/html
  - name: copy the expense conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted