- name: configure mysql sevrer
  hosts: mysql
  become: yes
  tasks:
  - name: install my sql server
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install mysql  librart
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: setup root password
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.kavyadev.shop
    register: mysql_info

  - name: print ec2_info
    ansible.builtin.debug:
      msg: print the o/p {{ mysql_info }}
